/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab7.ATU_Process;

import Lab7.algorithms.*;

@SuppressWarnings("unused")
public class Teaming_Algorithm {

	private static int team_size = 3;
	private int student_no = 10;
	private int team_no;
	public double k1_mean;
	public double k2_mean;
	
	public void formPreferenceLists(Team teams[], Student students[]) {
		//
	}
	
	public double totalMeanDeviation(Team team, Student student) {
		double new_team_k1_avg = (team.getK1() * team.getStudentNo() + student.getK1()) / (team.getStudentNo()+1);
		double new_team_k2_avg = (team.getK2() * team.getStudentNo() + student.getK2()) / (team.getStudentNo()+1);
		double k1_deviation = new_team_k1_avg - k1_mean;
		double k2_deviation = new_team_k2_avg - k2_mean;
		
		if (k1_deviation < 0) k1_deviation = 0 - k1_deviation;
		if (k2_deviation < 0) k2_deviation = 0 - k2_deviation;
		
		return (k1_deviation + k2_deviation);
	}
	
	public void updateMeans(Student students[], int n) {
		int k1_sum = 0;
		int k2_sum = 0;
		
		for (int i = 0; i < n; i++) {
			k1_sum += students[i].getK1();
			k2_sum += students[i].getK2();
		}
		
		k1_mean = k1_sum / n;
		k2_mean = k2_sum / n;
	}
	
	
	public void main(String args[]) {
		Student students[] = new Student[student_no];
		int student_k1[] = new int[student_no];
		for (int i = 0; i < student_no; i++) {
			String stu_id = "" + i;
			students[i] = new Student(stu_id, i+2, i+1);
			student_k1[i] = students[i].getK1();
		}
		team_no = student_no / team_size;
		Team teams[] = new Team[team_no];
		for (int i = 0; i < team_no; i++) 
			teams[i] = new Team(i);
		
		//MergeSort.sort(student_k1, 0, student_no);
	}
}

