/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.comp3111_project;

import org.junit.Test;

import com.example.comp3111_project.TeamingProcess;

import static org.junit.Assert.*;

@SuppressWarnings("unused")
public class TeamingProcess_test {
    @Test public void testSomeLibraryMethod() {
		TeamingProcess classUnderTest = new TeamingProcess();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
